services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sypets\RedirectsHelper\:
    resource: '../Classes/*'

  Sypets\RedirectsHelper\Command\RedirectsSanitizerCommand:
    tags:
      - name: 'console.command'
        command: 'redirects_helper:path2page'
        schedulable: false
